name: hisaz_cryptor
description: Windows app for crypting data. Maded by HAMIDVS for HISAZ team. D-20220401

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.1
  encrypt: ^5.0.1
  get: ^4.6.1
  ftpconnect: ^1.0.0
  file_picker: ^4.5.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/